### ISSUE TITLE
GameObject Attributes

### ISSUE THREAD

**Issue by carloscurotto** [lfrinaldi/template-tp-grupal#23]
En la clase GameObject hay algunos atributos que usan notacion hungara, es decir, incluyen el tipo de dato como parte del nombre de las variables:

private Map<String, GameObject> **childrenMap** = new HashMap<>();
private List<GameObject> **childrenList** = new ArrayList<>();
private Map<String, String> **attributesMap** = new HashMap<>();

No creen que seria mas claro incluso hacer algo asi?

private Map<String, GameObject> **children** = new HashMap<>();
private Map<String, String> **attributes** = new HashMap<>();

**Comment by carloscurotto** [comment]
Otra cosa que veo es que tienen dos estructuras para guardar children, un mapa y una lista, el problema de eso es que hay que mantener las dos, es necesario las dos?

**Comment by claucapo** [comment]
Si, un error de diseño al poner un mapa y necesitabamos un estructura
ordenada..

**Comment by nicolascian** [comment]
Se elimina childrenMap de GameObject bf3a0da

**Comment by nicolascian** [comment]
Se cambia de nombre childrenList (3d8d6af) y attributesMap (70b6a6d)
